---

- name: Patch all CentOS servers to most current version of installed software
  yum:
    name: "*"
    state: latest
  when: "'CentOS' in ansible_distribution"

- name: Patch all Suse servers to most current version of installed software
  zypper:
    name: "*"
    state: latest
  when: "'SUSE' in ansible_distribution"

- name: Patch all debian based servers
  apt:
    name: "*"
    state: latest
  when: "'Kali' in ansible_distribution"