---

- name: Running setup to gather variables
  setup:

- name: Group by Major Distribution
  group_by:
    key: "{{ansible_distribution}}{{ ansible_distribution_major_version }}"

- name: Show all groups
  debug:
    var: groups
